### ISSUE TITLE
Can't install using pip and virtualenv

### ISSUE THREAD

**Issue by alxppp** [midnightSuyama/instagram-explore#1]
Installation using pip and virtualenv fails with this error:

```
pip install instagram-explore
Collecting instagram-explore
  Using cached instagram-explore-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/69/gp01p42j0_b2ctq0v5dpzf8m0000gn/T/pip-build-U3Mgno/instagram-explore/setup.py", line 3, in <module>
        import instagram_explore
      File "instagram_explore/__init__.py", line 3, in <module>
        from .explore import *
      File "instagram_explore/explore.py", line 2, in <module>
        import requests
    ImportError: No module named requests

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/69/gp01p42j0_b2ctq0v5dpzf8m0000gn/T/pip-build-U3Mgno/instagram-explore/
```

**Comment by midnightSuyama** [comment]
The cause  is `ImportError: No module named requests`.

Please try:

```
$ pip install requests
$ pip install instagram-explore
```

**Comment by rdvo** [comment]
ImportError: No module named instagram_explore

why?
